services:
  averbacao-service:
    container_name: averbacao-service
    image: averbacao-service
    build:
      context: ./AverbacaoService/src
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:80
    networks:
      - averbacao-network
    depends_on:
      - averbacao-sqlserver
      
  averbacao-sqlserver:
    container_name: averbacao-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: D3vP@ss!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - averbacao-network
  
   averbacao-workflow-service:
     container_name: averbacao-workflow
     image: averbacao-workflow-service
     build:
       context: ./AverbacaoWorkflowService/src
       dockerfile: Dockerfile
     networks:
       - averbacao-network
     depends_on:
       - averbacao-service

volumes:
  sqlserver_data:

networks:
  averbacao-network:
    driver: bridge